### ISSUE TITLE
关于本实验中imagenet数据集的问题

### ISSUE THREAD

**Issue by itzhuang** [bytedance/MRECG#1]
您好，我在读本实验论文的时候发现论文中提到了`calibration data`这个概念，这是不是意味着复现代码数据集不是原本的1k的imagenet数据集，我在哪里可以找到这个数据集呢？谢谢。

**Comment by BobxmuMa** [comment]
> 您好，我在读本实验论文的时候发现论文中提到了`calibration data`这个概念，这是不是意味着复现代码数据集不是原本的1k的imagenet数据集，我在哪里可以找到这个数据集呢？谢谢。

本文的校准数据(calibration data)是从ImageNet 1k的训练数据中提取了几个batch作为校准数据集，具体提取方式请见：https://github.com/bytedance/MRECG/blob/6e48c483776a8175164f965e7b765a6c7193312c/ptq_main.py#L35

**Comment by itzhuang** [comment]
> > 您好，我在读本实验论文的时候发现论文中提到了`calibration data`这个概念，这是不是意味着复现代码数据集不是原本的1k的imagenet数据集，我在哪里可以找到这个数据集呢？谢谢。
> 
> 本文的校准数据(calibration data)是从ImageNet 1k的训练数据中提取了几个batch作为校准数据集，具体提取方式请见：
> 
> https://github.com/bytedance/MRECG/blob/6e48c483776a8175164f965e7b765a6c7193312c/ptq_main.py#L35

了解了，非常感谢。
