### ISSUE TITLE
算法通用性以及是否支持layer-wise量化

### ISSUE THREAD

**Issue by sdreamforchen** [bytedance/MRECG#3]
大佬，您好！ 请问你这个算法是通用的吗？  支持layer-wise的量化吗？ 不知道对目标检测识别是不是也同样有效

**Comment by BobxmuMa** [comment]
感谢你的关注。MRECG在不同的模型以及不同的比特配置上是通用的。layer-wise的情况loss振荡曲线相比block-wise更为复杂，我们没有在layer-wise上做尝试。同样我们也只在分类任务上测试了算法的有效性。

如果你感兴趣的话，可以试一下layer-wise量化的联合优化以及目标检测任务上的效果。

**Comment by sdreamforchen** [comment]
> 感谢你的关注。MRECG在不同的模型以及不同的比特配置上是通用的。layer-wise的情况loss振荡曲线相比block-wise更为复杂，我们没有在layer-wise上做尝试。同样我们也只在分类任务上测试了算法的有效性。
> 
> 如果你感兴趣的话，可以试一下layer-wise量化的联合优化以及目标检测任务上的效果。

您好。你提到的block-wise等效于channel-wise吗？

**Comment by BobxmuMa** [comment]
> > 感谢你的关注。MRECG在不同的模型以及不同的比特配置上是通用的。layer-wise的情况loss振荡曲线相比block-wise更为复杂，我们没有在layer-wise上做尝试。同样我们也只在分类任务上测试了算法的有效性。
> > 如果你感兴趣的话，可以试一下layer-wise量化的联合优化以及目标检测任务上的效果。
> 
> 您好。你提到的block-wise等效于channel-wise吗？

我这里的block-wise和layer-wise指的是PTQ重构的粒度。layer-wise指的是逐层重构，block-wise指的是逐block重构。如果你说的layer-wise是量化参数的粒度的话，这个我在所有的模型上用的是默认的配置做的实验来与其他算法保持一致，即权重per-channel，激活per-layer。
