### ISSUE TITLE
scheme表示的含义是什么

### ISSUE THREAD

**Issue by xd1073321804** [bytedance/MRECG#4]
您好，scheme表示的是联合重建的粒度吗，比如rs18_2_4的scheme是"[1, 2, (3, 3), (4, 4), 5, 6, 7, 8]"，里面的具体数字是什么意思呢，麻烦您解答下

**Comment by BobxmuMa** [comment]
是的，scheme是联合重建的粒度。这里的数字指代的是联合重建后的module序列。比如(3, 3)指代的是原始模型的第3个，第4个block组合成新的第3个module进行联合重建。

**Comment by xd1073321804** [comment]
好的，谢谢啦
